homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC

# Show links to resources in log and frontend
introduction:

# Track the sun
sun:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend
conversation:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history: