homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.net

  # Location required to calculate the time the sun rises and sets
  latitude: 43.610769
  longitude: 3.876716

  # C for Celcius, F for Fahrenheit
  temperature_unit: C

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  # Name of the location where Home Assistant is running
  name: Home

http:
#    api_password: mypass
#    # Set to 1 to enable development mode
  development: 1

##########################################
# Sensor devices
##########################################
sun:

sensor:
  platform: systemmonitor
  resources:
    - type: 'disk_use_percent'
      arg: '/'
    - type: 'disk_use_percent'
      arg: '/home'
    - type: 'disk_use'
      arg: '/home'
    - type: 'disk_free'
      arg: '/'
    - type: 'memory_use_percent'
    - type: 'memory_use'
    - type: 'memory_free'
    - type: 'processor_use'
    - type: 'process'
      arg: 'octave-cli'

sensor 2:
  platform: openweathermap
  api_key: 5e7ad580eef34c4ce228bd8fb8440515
  forecast: 1
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain
    - snow

sensor 3:
  platform: swiss_public_transport
  from: 008400319
  to: 008302713

# Time
sensor 4:
  platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'

##########################################
# Services
##########################################
introduction:
frontend:
discovery:
history:
conversation:
logbook:


# Notification
notify:
  name: tosyslog
  platform: syslog
  facility: syslog
  option: pid
  priority: 0

#mqtt:
#  broker: http://test.mosquitto.org/
#  port: 1883
#  client_id: home-assistant-1
#  keepalive: 60

#light:
##  platform: hue

#device_tracker:
#  # Scan local network for testing new device
#  platform: nmap_tracker
#  hosts: 192.168.252.0/24
#  track_new_devices: yes

#chromecast:
#  # Google chromecast dongle

#switch:
#  platform: wemo

#thermostat:
#  platform: nest
#  # Required: username and password that are used to login to the Nest thermostat.
#  username: myemail@mydomain.com
#  password: mypassword

#downloader:
#  download_dir: downloads
#
#notify:
#  platform: pushbullet
#  api_key: ABCDEFGHJKLMNOPQRSTUVXYZ
#
#device_sun_light_trigger:
#  # Optional: specify a specific light/group of lights that has to be turned on
#  light_group: group.living_room
#  # Optional: specify which light profile to use when turning lights on
#  light_profile: relax
#  # Optional: disable lights being turned off when everybody leaves the house
#  # disable_turn_off: 1
#
## A comma separated list of states that have to be tracked as a single group
## Grouped states should share the same type of states (ON/OFF or HOME/NOT_HOME)
group:
  time:
    - sensor.date__time
    - sensor.time_utc
    - sensor.time_beat
  process:
   - sensor.cpu_use
   - sensor.disk_free_
   - sensor.ram_free
#
#process:
#  # items are which processes to look for: <entity_id>: <search string within ps>
#  xbmc: XBMC.App
#
#example:
#
#simple_alarm:
#  # Which light/light group has to flash when a known device comes home
#  known_light: light.Bowl
#  # Which light/light group has to flash red when light turns on while no one home
#  unknown_light: group.living_room
#
#browser:
#
#keyboard:
#
#automation:
#  platform: state
#  alias: Sun starts shining
#
#  state_entity_id: sun.sun
#  # Next two are optional, omit to match all
#  state_from: below_horizon
#  state_to: above_horizon
#
#  execute_service: light.turn_off
#  service_entity_id: group.living_room
#
#automation 2:
#  platform: time
#  alias: Beer o Clock
#
#  time_hours: 16
#  time_minutes: 0
#  time_seconds: 0
#
#  execute_service: notify.notify
#  service_data:
#    message: It's 4, time for beer!
#
#
#script:
#  # Turns on the bedroom lights and then the living room lights 1 minute later
#  wakeup:
#    alias: Wake Up
#    sequence:
#      # alias is optional
#      - alias: Bedroom lights on
#        execute_service: light.turn_on
#        service_data:
#          entity_id: group.bedroom
#      - delay:
#          # supports seconds, milliseconds, minutes, hours, etc.
#          minutes: 1
#      - alias: Living room lights on
#        execute_service: light.turn_on
#        service_data:
#          entity_id: group.living_room
#
#scene:
#  - name: Romantic
#    entities:
#      light.tv_back_light: on
#      light.ceiling:
#        state: on
#        xy_color: [0.33, 0.66]
#        brightness: 200