FROM badele/debian-mybase
MAINTAINER Bruno Adelé "bruno@adele.im"

# Mosquitto
RUN apt-get install -y mosquitto mosquitto-clients

# Python3 stack
RUN apt-get install -y python3 python3-mosquitto python3-pip python3-setuptools